### ISSUE TITLE
Plan for mocha-parallel-tests release v2

### ISSUE THREAD

**Issue by 1999** [yandex/mocha-parallel-tests#126]
All of these thing are subject to v2 release of mocha-parallel-tests. Some of these things can be postponed however this is a core of release.

- [x] Support mocha peerDependencies 3-5 (#122)
- [x] Specify concurrency behaviour (#89, #108, #110, #115, #116)
- [x] Parallel mode: running mocha tests on multiple cores (#66, #80, #96)
- [x] Mimic mocha CLI behaviour by passing flags (#84)
- [x] Investigate current behaviour with retries: it(), describe() etc
- [x] TypeScript code

Would be great to have these things done however not a reason to postpone new major release.

- [x] Comparison with other similar libraries (#52)
- [x] Flaky Selenium tests (#99)
- [x] Investigate install errors on windows (#111)

**Comment by mpreethi90** [comment]
@1999  , Does the latest release contains support to mochawesome? I still have same empty html issue.

**Comment by 1999** [comment]
Not sure, I haven't checked it yet. Let's track this down in #113
